---
version: '3.5'

networks:
  dionysos:
services:
  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:14
    command: -p ${POSTGRES_PORT}
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgres-${RANDOM}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
